PUT http://localhost:9200/get-event/_doc/1
Content-Type: application/json

{
  "name": "yzh"
}

###
PUT http://localhost:9200/get-event/_mapping/
Content-Type: application/json

{
  "properties": {
    "host": {
      "type": "keyword"
    }
  }
}

###
GET http://localhost:9200/get-event/_mapping

### 已有类型设置新类型会报错
PUT http://localhost:9200/get-event/_mapping/
Content-Type: application/json

{
  "properties": {
    "host": {
      "type": "long"
    }
  }
}

###
PUT http://localhost:9200/get-event/_doc/2
Content-Type: application/json

{
  "name": "yzh",
  "host:": "192.168.0.1"
}

###
PUT http://localhost:9200/get-event/_doc/3
Content-Type: application/json

{
  "name": "yzh",
  "host:": "192.168.10.15"
}

###
GET http://localhost:9200/get-event/_search
Content-Type: application/json

{
  "query": {
    "query_string": {
      "query": "192"
    }
  }
}

###
GET http://localhost:9200/get-event/_search

### 设置时间类型
GET http://localhost:9200/get-event/_mapping

###
PUT http://localhost:9200/get-event/_mapping
Content-Type: application/json

{
  "properties": {
    "time": {
      "type": "date"
    }
  }
}

###
PUT http://localhost:9200/get-event/_mapping
Content-Type: application/json

{
  "properties": {
    "ts": {
      "type": "date",
      "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
    }
  }
}

###
GET http://localhost:9200/get-event/_search?size=1

###
PUT http://localhost:9200/get-event/_doc/4
Content-Type: application/json

{
  "name": "lcm",
  "time": 1576050803,
  "ts": "2019-12-11 15:53:40"
}

###
PUT http://localhost:9200/get-event/_doc/5
Content-Type: application/json

{
  "name": "lcm",
  "time": 1576050813,
  "ts": "2019-12-11 15:53:55"
}

###
GET http://localhost:9200/get-event/_search
Content-Type: application/json

{
  "size": 2,
  "sort": {
    "ts": "desc"
  }
}

###
GET http://localhost:9200/get-event/_mapping

###
PUT http://localhost:9200/get-event/_mapping
Content-Type: application/json

{
  "properties": {
    "tags": {
      "type": "text",
      "fields": {
        "verbatim": {
          "type": "keyword",
          "index": "not_analyzed"
        }
      }
    }
  }
}

### 多字段
PUT http://localhost:9200/get-event/_mapping
Content-Type: application/json

{
  "properties": {
    "nick": {
      "type": "text",
      "fields": {
        "verbatim": {
          "type": "keyword"
        }
      }
    }
  }
}

###
GET http://localhost:9200/get-event/_search
Content-Type:application/json

{
  "size": 1
}

###
PUT http://localhost:9200/get-event/_doc/6
Content-Type: application/json

{
  "nick": "hello world"
}

###
# 实验:将nick是这多字段
# nick -> "type":"text"
# nick.verbatim -> "type":"keyword"
# 查询 "query":"hello"
# 结果 nick->1  nick.verbatim->0
GET http://localhost:9200/get-event/_search
Content-Type: application/json

{
  "size": 0,
  "query": {
    "query_string": {
      "query": "hello",
      "default_field": "nick"
    }
  }
}

### 使用"_source"过滤器
GET http://localhost:9200/get-event/_search
Content-Type: application/json

{
  "size": 2,
  "_source": [
    "name"
  ]
}

###
GET http://localhost:9200/get-event/_doc/1

### 更新文档
GET http://localhost:9200/get-event/_search

### 更新文档（如果文档之前不存在则更新失败）
POST http://localhost:9200/get-event/_doc/2/_update
Content-Type: application/json

{
  "doc": {
    "name": "YZH"
  }
}

###
GET http://localhost:9200/get-event/_doc/2

### 使用upsert来更新不存在的文档
POST http://localhost:9200/get-event/_doc/7/_update
Content-Type: application/json

{
  "doc": {
    "name": "love xjj"
  },
  "upsert": {
    "host": "127.0.0.1",
    "name": "love xjj",
    "ts": "2019-12-11 17:50:55"
  }
}

###
GET http://localhost:9200/get-event/_doc/7

###
GET http://localhost:9200/get-event/_search

### 错误的索引
DELETE http://localhost:9200/get-event/_doc/7_update

### 控制版本 （外部版本控制）
### 使用外部版本控制时，传入的version必须大于文档的version，否则更新失败
PUT http://localhost:9200/get-event/_doc/7?version=3&version_type=external
Content-Type: application/json

{
  "doc": {
    "name": "love lcm"
  }
}

### 内部版本控制
### 使用内部版本控制的时候，传入的值必须等于文档的version,否则更新失败
POST http://localhost:9200/get-event/_doc/7/_update?version=3
Content-Type: application/json

{
  "doc": {
    "name": "love xyj"
  }
}

### 关闭与打开索引(并不删除)
POST  http://localhost:9200/get-event/_close

### 打开索引
POST http://localhost:9200/get-event/_open

###
POST http://localhost:9200/get-event/_doc/7/_update
Content-Type: application/json

{
  "doc": {
    "name": "love xjj"
  }
}

###
GET http://localhost:9200/get-event/_doc/7


###

