// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLogic struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogic) Reset()         { *m = UserLogic{} }
func (m *UserLogic) String() string { return proto.CompactTextString(m) }
func (*UserLogic) ProtoMessage()    {}
func (*UserLogic) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserLogic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogic.Unmarshal(m, b)
}
func (m *UserLogic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogic.Marshal(b, m, deterministic)
}
func (m *UserLogic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogic.Merge(m, src)
}
func (m *UserLogic) XXX_Size() int {
	return xxx_messageInfo_UserLogic.Size(m)
}
func (m *UserLogic) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogic.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogic proto.InternalMessageInfo

type UserLogic_Login struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogic_Login) Reset()         { *m = UserLogic_Login{} }
func (m *UserLogic_Login) String() string { return proto.CompactTextString(m) }
func (*UserLogic_Login) ProtoMessage()    {}
func (*UserLogic_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 0}
}

func (m *UserLogic_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogic_Login.Unmarshal(m, b)
}
func (m *UserLogic_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogic_Login.Marshal(b, m, deterministic)
}
func (m *UserLogic_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogic_Login.Merge(m, src)
}
func (m *UserLogic_Login) XXX_Size() int {
	return xxx_messageInfo_UserLogic_Login.Size(m)
}
func (m *UserLogic_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogic_Login.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogic_Login proto.InternalMessageInfo

func (m *UserLogic_Login) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserLogic_Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLogic_LoginAck struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogic_LoginAck) Reset()         { *m = UserLogic_LoginAck{} }
func (m *UserLogic_LoginAck) String() string { return proto.CompactTextString(m) }
func (*UserLogic_LoginAck) ProtoMessage()    {}
func (*UserLogic_LoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 1}
}

func (m *UserLogic_LoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogic_LoginAck.Unmarshal(m, b)
}
func (m *UserLogic_LoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogic_LoginAck.Marshal(b, m, deterministic)
}
func (m *UserLogic_LoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogic_LoginAck.Merge(m, src)
}
func (m *UserLogic_LoginAck) XXX_Size() int {
	return xxx_messageInfo_UserLogic_LoginAck.Size(m)
}
func (m *UserLogic_LoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogic_LoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogic_LoginAck proto.InternalMessageInfo

func (m *UserLogic_LoginAck) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*UserLogic)(nil), "pb.UserLogic")
	proto.RegisterType((*UserLogic_Login)(nil), "pb.UserLogic.Login")
	proto.RegisterType((*UserLogic_LoginAck)(nil), "pb.UserLogic.LoginAck")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xca, 0xe1, 0xe2, 0x0c, 0x2d,
	0x4e, 0x2d, 0xf2, 0xc9, 0x4f, 0xcf, 0x4c, 0x96, 0xb2, 0xe5, 0x62, 0x05, 0x31, 0xf2, 0x84, 0x24,
	0xb8, 0xd8, 0x1d, 0x93, 0x93, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x60, 0x5c, 0x21, 0x29, 0x2e, 0x8e, 0x80, 0xc4, 0xe2, 0xe2, 0xf2, 0xfc, 0xa2, 0x14, 0x09, 0x26,
	0xb0, 0x14, 0x9c, 0x2f, 0xa5, 0xc0, 0xc5, 0x01, 0xd6, 0xee, 0x98, 0x9c, 0x2d, 0x24, 0xc2, 0xc5,
	0x1a, 0x92, 0x9f, 0x9d, 0x9a, 0x07, 0xd5, 0x0f, 0xe1, 0x24, 0xb1, 0x81, 0x2d, 0x36, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xb6, 0xf7, 0xcc, 0x01, 0x86, 0x00, 0x00, 0x00,
}
