package main

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *Student) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "ID"
	o = append(o, 0x85, 0xa2, 0x49, 0x44)
	o = msgp.AppendUint32(o, z.ID)
	// string "Name"
	o = append(o, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "Work"
	o = append(o, 0xa4, 0x57, 0x6f, 0x72, 0x6b)
	o = msgp.AppendString(o, z.Work)
	// string "Age"
	o = append(o, 0xa3, 0x41, 0x67, 0x65)
	o = msgp.AppendUint16(o, z.Age)
	// string "Birthday"
	o = append(o, 0xa8, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79)
	o = msgp.AppendString(o, z.Birthday)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Student) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				return
			}
		case "Name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "Work":
			z.Work, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "Age":
			z.Age, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				return
			}
		case "Birthday":
			z.Birthday, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Student) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 5 + msgp.StringPrefixSize + len(z.Name) + 5 + msgp.StringPrefixSize + len(z.Work) + 4 + msgp.Uint16Size + 9 + msgp.StringPrefixSize + len(z.Birthday)
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Teacher) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "id"
	o = append(o, 0x85, 0xa2, 0x69, 0x64)
	o = msgp.AppendUint32(o, z.ID)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "work"
	o = append(o, 0xa4, 0x77, 0x6f, 0x72, 0x6b)
	o = msgp.AppendString(o, z.Work)
	// string "age"
	o = append(o, 0xa3, 0x61, 0x67, 0x65)
	o = msgp.AppendUint16(o, z.Age)
	// string "birthday"
	o = append(o, 0xa8, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79)
	o = msgp.AppendString(o, z.Birthday)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Teacher) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			return
		}
		switch msgp.UnsafeString(field) {
		case "id":
			z.ID, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "work":
			z.Work, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		case "age":
			z.Age, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				return
			}
		case "birthday":
			z.Birthday, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Teacher) Msgsize() (s int) {
	s = 1 + 3 + msgp.Uint32Size + 5 + msgp.StringPrefixSize + len(z.Name) + 5 + msgp.StringPrefixSize + len(z.Work) + 4 + msgp.Uint16Size + 9 + msgp.StringPrefixSize + len(z.Birthday)
	return
}
