// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gift.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Manager struct {
}

func (m *Manager) Reset()         { *m = Manager{} }
func (m *Manager) String() string { return proto.CompactTextString(m) }
func (*Manager) ProtoMessage()    {}
func (*Manager) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0}
}
func (m *Manager) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager.Merge(dst, src)
}
func (m *Manager) XXX_Size() int {
	return m.Size()
}
func (m *Manager) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager.DiscardUnknown(m)
}

var xxx_messageInfo_Manager proto.InternalMessageInfo

type Manager_Nil struct {
}

func (m *Manager_Nil) Reset()         { *m = Manager_Nil{} }
func (m *Manager_Nil) String() string { return proto.CompactTextString(m) }
func (*Manager_Nil) ProtoMessage()    {}
func (*Manager_Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 0}
}
func (m *Manager_Nil) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_Nil.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_Nil.Merge(dst, src)
}
func (m *Manager_Nil) XXX_Size() int {
	return m.Size()
}
func (m *Manager_Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_Nil proto.InternalMessageInfo

type Manager_Item struct {
	Id  uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Num int32  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (m *Manager_Item) Reset()         { *m = Manager_Item{} }
func (m *Manager_Item) String() string { return proto.CompactTextString(m) }
func (*Manager_Item) ProtoMessage()    {}
func (*Manager_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 1}
}
func (m *Manager_Item) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_Item.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_Item.Merge(dst, src)
}
func (m *Manager_Item) XXX_Size() int {
	return m.Size()
}
func (m *Manager_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_Item proto.InternalMessageInfo

func (m *Manager_Item) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Manager_Item) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type Manager_GenReq struct {
	FixCode      string          `protobuf:"bytes,1,opt,name=FixCode,proto3" json:"FixCode,omitempty"`
	Num          uint32          `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	StartTime    int64           `protobuf:"varint,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime      int64           `protobuf:"varint,4,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	TimesPerUser uint32          `protobuf:"varint,5,opt,name=TimesPerUser,proto3" json:"TimesPerUser,omitempty"`
	ZoneIds      []uint32        `protobuf:"varint,6,rep,packed,name=ZoneIds" json:"ZoneIds,omitempty"`
	Items        []*Manager_Item `protobuf:"bytes,7,rep,name=Items" json:"Items,omitempty"`
	GenerateTime int64           `protobuf:"varint,8,opt,name=GenerateTime,proto3" json:"GenerateTime,omitempty"`
}

func (m *Manager_GenReq) Reset()         { *m = Manager_GenReq{} }
func (m *Manager_GenReq) String() string { return proto.CompactTextString(m) }
func (*Manager_GenReq) ProtoMessage()    {}
func (*Manager_GenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 2}
}
func (m *Manager_GenReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_GenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_GenReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_GenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_GenReq.Merge(dst, src)
}
func (m *Manager_GenReq) XXX_Size() int {
	return m.Size()
}
func (m *Manager_GenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_GenReq.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_GenReq proto.InternalMessageInfo

func (m *Manager_GenReq) GetFixCode() string {
	if m != nil {
		return m.FixCode
	}
	return ""
}

func (m *Manager_GenReq) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Manager_GenReq) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Manager_GenReq) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Manager_GenReq) GetTimesPerUser() uint32 {
	if m != nil {
		return m.TimesPerUser
	}
	return 0
}

func (m *Manager_GenReq) GetZoneIds() []uint32 {
	if m != nil {
		return m.ZoneIds
	}
	return nil
}

func (m *Manager_GenReq) GetItems() []*Manager_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Manager_GenReq) GetGenerateTime() int64 {
	if m != nil {
		return m.GenerateTime
	}
	return 0
}

type Manager_GenResp struct {
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (m *Manager_GenResp) Reset()         { *m = Manager_GenResp{} }
func (m *Manager_GenResp) String() string { return proto.CompactTextString(m) }
func (*Manager_GenResp) ProtoMessage()    {}
func (*Manager_GenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 3}
}
func (m *Manager_GenResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_GenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_GenResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_GenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_GenResp.Merge(dst, src)
}
func (m *Manager_GenResp) XXX_Size() int {
	return m.Size()
}
func (m *Manager_GenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_GenResp.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_GenResp proto.InternalMessageInfo

func (m *Manager_GenResp) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Manager_ExportReq struct {
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (m *Manager_ExportReq) Reset()         { *m = Manager_ExportReq{} }
func (m *Manager_ExportReq) String() string { return proto.CompactTextString(m) }
func (*Manager_ExportReq) ProtoMessage()    {}
func (*Manager_ExportReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 4}
}
func (m *Manager_ExportReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_ExportReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_ExportReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_ExportReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_ExportReq.Merge(dst, src)
}
func (m *Manager_ExportReq) XXX_Size() int {
	return m.Size()
}
func (m *Manager_ExportReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_ExportReq.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_ExportReq proto.InternalMessageInfo

func (m *Manager_ExportReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Manager_CodeStatus struct {
	Code   string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ZoneId uint32 `protobuf:"varint,3,opt,name=ZoneId,proto3" json:"ZoneId,omitempty"`
}

func (m *Manager_CodeStatus) Reset()         { *m = Manager_CodeStatus{} }
func (m *Manager_CodeStatus) String() string { return proto.CompactTextString(m) }
func (*Manager_CodeStatus) ProtoMessage()    {}
func (*Manager_CodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 5}
}
func (m *Manager_CodeStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_CodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_CodeStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_CodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_CodeStatus.Merge(dst, src)
}
func (m *Manager_CodeStatus) XXX_Size() int {
	return m.Size()
}
func (m *Manager_CodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_CodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_CodeStatus proto.InternalMessageInfo

func (m *Manager_CodeStatus) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Manager_CodeStatus) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Manager_CodeStatus) GetZoneId() uint32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

type Manager_ExportResp struct {
	Details []*Manager_CodeStatus `protobuf:"bytes,1,rep,name=Details" json:"Details,omitempty"`
}

func (m *Manager_ExportResp) Reset()         { *m = Manager_ExportResp{} }
func (m *Manager_ExportResp) String() string { return proto.CompactTextString(m) }
func (*Manager_ExportResp) ProtoMessage()    {}
func (*Manager_ExportResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 6}
}
func (m *Manager_ExportResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_ExportResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_ExportResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_ExportResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_ExportResp.Merge(dst, src)
}
func (m *Manager_ExportResp) XXX_Size() int {
	return m.Size()
}
func (m *Manager_ExportResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_ExportResp.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_ExportResp proto.InternalMessageInfo

func (m *Manager_ExportResp) GetDetails() []*Manager_CodeStatus {
	if m != nil {
		return m.Details
	}
	return nil
}

type Manager_GiftInfo struct {
	Id      uint32          `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Used    uint32          `protobuf:"varint,2,opt,name=Used,proto3" json:"Used,omitempty"`
	GenInfo *Manager_GenReq `protobuf:"bytes,3,opt,name=GenInfo" json:"GenInfo,omitempty"`
}

func (m *Manager_GiftInfo) Reset()         { *m = Manager_GiftInfo{} }
func (m *Manager_GiftInfo) String() string { return proto.CompactTextString(m) }
func (*Manager_GiftInfo) ProtoMessage()    {}
func (*Manager_GiftInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 7}
}
func (m *Manager_GiftInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_GiftInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_GiftInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_GiftInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_GiftInfo.Merge(dst, src)
}
func (m *Manager_GiftInfo) XXX_Size() int {
	return m.Size()
}
func (m *Manager_GiftInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_GiftInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_GiftInfo proto.InternalMessageInfo

func (m *Manager_GiftInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Manager_GiftInfo) GetUsed() uint32 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *Manager_GiftInfo) GetGenInfo() *Manager_GenReq {
	if m != nil {
		return m.GenInfo
	}
	return nil
}

type Manager_ListResp struct {
	Details []*Manager_GiftInfo `protobuf:"bytes,1,rep,name=Details" json:"Details,omitempty"`
}

func (m *Manager_ListResp) Reset()         { *m = Manager_ListResp{} }
func (m *Manager_ListResp) String() string { return proto.CompactTextString(m) }
func (*Manager_ListResp) ProtoMessage()    {}
func (*Manager_ListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 8}
}
func (m *Manager_ListResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_ListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_ListResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_ListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_ListResp.Merge(dst, src)
}
func (m *Manager_ListResp) XXX_Size() int {
	return m.Size()
}
func (m *Manager_ListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_ListResp.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_ListResp proto.InternalMessageInfo

func (m *Manager_ListResp) GetDetails() []*Manager_GiftInfo {
	if m != nil {
		return m.Details
	}
	return nil
}

type Manager_DeleteReq struct {
	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (m *Manager_DeleteReq) Reset()         { *m = Manager_DeleteReq{} }
func (m *Manager_DeleteReq) String() string { return proto.CompactTextString(m) }
func (*Manager_DeleteReq) ProtoMessage()    {}
func (*Manager_DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{0, 9}
}
func (m *Manager_DeleteReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Manager_DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Manager_DeleteReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Manager_DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manager_DeleteReq.Merge(dst, src)
}
func (m *Manager_DeleteReq) XXX_Size() int {
	return m.Size()
}
func (m *Manager_DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Manager_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_Manager_DeleteReq proto.InternalMessageInfo

func (m *Manager_DeleteReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type VerifyReq struct {
	Code   string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Zone   uint32 `protobuf:"varint,2,opt,name=Zone,proto3" json:"Zone,omitempty"`
	UserId uint64 `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{1}
}
func (m *VerifyReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifyReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReq.Merge(dst, src)
}
func (m *VerifyReq) XXX_Size() int {
	return m.Size()
}
func (m *VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReq proto.InternalMessageInfo

func (m *VerifyReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *VerifyReq) GetZone() uint32 {
	if m != nil {
		return m.Zone
	}
	return 0
}

func (m *VerifyReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type VerifyResp struct {
	Status uint32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (m *VerifyResp) Reset()         { *m = VerifyResp{} }
func (m *VerifyResp) String() string { return proto.CompactTextString(m) }
func (*VerifyResp) ProtoMessage()    {}
func (*VerifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{2}
}
func (m *VerifyResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifyResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *VerifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResp.Merge(dst, src)
}
func (m *VerifyResp) XXX_Size() int {
	return m.Size()
}
func (m *VerifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResp proto.InternalMessageInfo

func (m *VerifyResp) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type SyncReq struct {
	Zone uint32 `protobuf:"varint,1,opt,name=Zone,proto3" json:"Zone,omitempty"`
}

func (m *SyncReq) Reset()         { *m = SyncReq{} }
func (m *SyncReq) String() string { return proto.CompactTextString(m) }
func (*SyncReq) ProtoMessage()    {}
func (*SyncReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{3}
}
func (m *SyncReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SyncReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncReq.Merge(dst, src)
}
func (m *SyncReq) XXX_Size() int {
	return m.Size()
}
func (m *SyncReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncReq.DiscardUnknown(m)
}

var xxx_messageInfo_SyncReq proto.InternalMessageInfo

func (m *SyncReq) GetZone() uint32 {
	if m != nil {
		return m.Zone
	}
	return 0
}

type SyncResp struct {
	Info   []*Manager_GiftInfo `protobuf:"bytes,1,rep,name=Info" json:"Info,omitempty"`
	Status uint32              `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (m *SyncResp) Reset()         { *m = SyncResp{} }
func (m *SyncResp) String() string { return proto.CompactTextString(m) }
func (*SyncResp) ProtoMessage()    {}
func (*SyncResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gift_d27fbfcd8a6c500f, []int{4}
}
func (m *SyncResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SyncResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncResp.Merge(dst, src)
}
func (m *SyncResp) XXX_Size() int {
	return m.Size()
}
func (m *SyncResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncResp.DiscardUnknown(m)
}

var xxx_messageInfo_SyncResp proto.InternalMessageInfo

func (m *SyncResp) GetInfo() []*Manager_GiftInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *SyncResp) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Manager)(nil), "pb.Manager")
	proto.RegisterType((*Manager_Nil)(nil), "pb.Manager.Nil")
	proto.RegisterType((*Manager_Item)(nil), "pb.Manager.Item")
	proto.RegisterType((*Manager_GenReq)(nil), "pb.Manager.GenReq")
	proto.RegisterType((*Manager_GenResp)(nil), "pb.Manager.GenResp")
	proto.RegisterType((*Manager_ExportReq)(nil), "pb.Manager.ExportReq")
	proto.RegisterType((*Manager_CodeStatus)(nil), "pb.Manager.CodeStatus")
	proto.RegisterType((*Manager_ExportResp)(nil), "pb.Manager.ExportResp")
	proto.RegisterType((*Manager_GiftInfo)(nil), "pb.Manager.GiftInfo")
	proto.RegisterType((*Manager_ListResp)(nil), "pb.Manager.ListResp")
	proto.RegisterType((*Manager_DeleteReq)(nil), "pb.Manager.DeleteReq")
	proto.RegisterType((*VerifyReq)(nil), "pb.VerifyReq")
	proto.RegisterType((*VerifyResp)(nil), "pb.VerifyResp")
	proto.RegisterType((*SyncReq)(nil), "pb.SyncReq")
	proto.RegisterType((*SyncResp)(nil), "pb.SyncResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GiftServiceClient is the client API for GiftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GiftServiceClient interface {
	Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (GiftService_SyncClient, error)
	CodeVerify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyResp, error)
	Generate(ctx context.Context, in *Manager_GenReq, opts ...grpc.CallOption) (*Manager_GenResp, error)
	List(ctx context.Context, in *Manager_Nil, opts ...grpc.CallOption) (*Manager_ListResp, error)
	Export(ctx context.Context, in *Manager_ExportReq, opts ...grpc.CallOption) (*Manager_ExportResp, error)
	Delete(ctx context.Context, in *Manager_DeleteReq, opts ...grpc.CallOption) (*Manager_Nil, error)
}

type giftServiceClient struct {
	cc *grpc.ClientConn
}

func NewGiftServiceClient(cc *grpc.ClientConn) GiftServiceClient {
	return &giftServiceClient{cc}
}

func (c *giftServiceClient) Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (GiftService_SyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GiftService_serviceDesc.Streams[0], "/pb.GiftService/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &giftServiceSyncClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GiftService_SyncClient interface {
	Recv() (*SyncResp, error)
	grpc.ClientStream
}

type giftServiceSyncClient struct {
	grpc.ClientStream
}

func (x *giftServiceSyncClient) Recv() (*SyncResp, error) {
	m := new(SyncResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *giftServiceClient) CodeVerify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyResp, error) {
	out := new(VerifyResp)
	err := c.cc.Invoke(ctx, "/pb.GiftService/CodeVerify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftServiceClient) Generate(ctx context.Context, in *Manager_GenReq, opts ...grpc.CallOption) (*Manager_GenResp, error) {
	out := new(Manager_GenResp)
	err := c.cc.Invoke(ctx, "/pb.GiftService/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftServiceClient) List(ctx context.Context, in *Manager_Nil, opts ...grpc.CallOption) (*Manager_ListResp, error) {
	out := new(Manager_ListResp)
	err := c.cc.Invoke(ctx, "/pb.GiftService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftServiceClient) Export(ctx context.Context, in *Manager_ExportReq, opts ...grpc.CallOption) (*Manager_ExportResp, error) {
	out := new(Manager_ExportResp)
	err := c.cc.Invoke(ctx, "/pb.GiftService/Export", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *giftServiceClient) Delete(ctx context.Context, in *Manager_DeleteReq, opts ...grpc.CallOption) (*Manager_Nil, error) {
	out := new(Manager_Nil)
	err := c.cc.Invoke(ctx, "/pb.GiftService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GiftServiceServer is the server API for GiftService service.
type GiftServiceServer interface {
	Sync(*SyncReq, GiftService_SyncServer) error
	CodeVerify(context.Context, *VerifyReq) (*VerifyResp, error)
	Generate(context.Context, *Manager_GenReq) (*Manager_GenResp, error)
	List(context.Context, *Manager_Nil) (*Manager_ListResp, error)
	Export(context.Context, *Manager_ExportReq) (*Manager_ExportResp, error)
	Delete(context.Context, *Manager_DeleteReq) (*Manager_Nil, error)
}

func RegisterGiftServiceServer(s *grpc.Server, srv GiftServiceServer) {
	s.RegisterService(&_GiftService_serviceDesc, srv)
}

func _GiftService_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GiftServiceServer).Sync(m, &giftServiceSyncServer{stream})
}

type GiftService_SyncServer interface {
	Send(*SyncResp) error
	grpc.ServerStream
}

type giftServiceSyncServer struct {
	grpc.ServerStream
}

func (x *giftServiceSyncServer) Send(m *SyncResp) error {
	return x.ServerStream.SendMsg(m)
}

func _GiftService_CodeVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServiceServer).CodeVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GiftService/CodeVerify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServiceServer).CodeVerify(ctx, req.(*VerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Manager_GenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GiftService/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServiceServer).Generate(ctx, req.(*Manager_GenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Manager_Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GiftService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServiceServer).List(ctx, req.(*Manager_Nil))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftService_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Manager_ExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServiceServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GiftService/Export",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServiceServer).Export(ctx, req.(*Manager_ExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GiftService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Manager_DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GiftServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GiftService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GiftServiceServer).Delete(ctx, req.(*Manager_DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GiftService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GiftService",
	HandlerType: (*GiftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CodeVerify",
			Handler:    _GiftService_CodeVerify_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _GiftService_Generate_Handler,
		},
		{
			MethodName: "List",
			Handler:    _GiftService_List_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _GiftService_Export_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GiftService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _GiftService_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gift.proto",
}

func (m *Manager) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *Manager_Nil) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_Nil) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *Manager_Item) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_Item) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Id))
	}
	if m.Num != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Num))
	}
	return i, nil
}

func (m *Manager_GenReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_GenReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.FixCode) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGift(dAtA, i, uint64(len(m.FixCode)))
		i += copy(dAtA[i:], m.FixCode)
	}
	if m.Num != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Num))
	}
	if m.StartTime != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.EndTime))
	}
	if m.TimesPerUser != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.TimesPerUser))
	}
	if len(m.ZoneIds) > 0 {
		dAtA2 := make([]byte, len(m.ZoneIds)*10)
		var j1 int
		for _, num := range m.ZoneIds {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x32
		i++
		i = encodeVarintGift(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.Items) > 0 {
		for _, msg := range m.Items {
			dAtA[i] = 0x3a
			i++
			i = encodeVarintGift(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.GenerateTime != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.GenerateTime))
	}
	return i, nil
}

func (m *Manager_GenResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_GenResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *Manager_ExportReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_ExportReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *Manager_CodeStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_CodeStatus) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Code) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGift(dAtA, i, uint64(len(m.Code)))
		i += copy(dAtA[i:], m.Code)
	}
	if m.UserId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.UserId))
	}
	if m.ZoneId != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.ZoneId))
	}
	return i, nil
}

func (m *Manager_ExportResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_ExportResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Details) > 0 {
		for _, msg := range m.Details {
			dAtA[i] = 0xa
			i++
			i = encodeVarintGift(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *Manager_GiftInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_GiftInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Id))
	}
	if m.Used != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Used))
	}
	if m.GenInfo != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.GenInfo.Size()))
		n3, err := m.GenInfo.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}

func (m *Manager_ListResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_ListResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Details) > 0 {
		for _, msg := range m.Details {
			dAtA[i] = 0xa
			i++
			i = encodeVarintGift(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *Manager_DeleteReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Manager_DeleteReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *VerifyReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifyReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Code) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintGift(dAtA, i, uint64(len(m.Code)))
		i += copy(dAtA[i:], m.Code)
	}
	if m.Zone != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Zone))
	}
	if m.UserId != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.UserId))
	}
	return i, nil
}

func (m *VerifyResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifyResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Status))
	}
	return i, nil
}

func (m *SyncReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Zone != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Zone))
	}
	return i, nil
}

func (m *SyncResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Info) > 0 {
		for _, msg := range m.Info {
			dAtA[i] = 0xa
			i++
			i = encodeVarintGift(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Status != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGift(dAtA, i, uint64(m.Status))
	}
	return i, nil
}

func encodeVarintGift(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Manager) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Manager_Nil) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Manager_Item) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGift(uint64(m.Id))
	}
	if m.Num != 0 {
		n += 1 + sovGift(uint64(m.Num))
	}
	return n
}

func (m *Manager_GenReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FixCode)
	if l > 0 {
		n += 1 + l + sovGift(uint64(l))
	}
	if m.Num != 0 {
		n += 1 + sovGift(uint64(m.Num))
	}
	if m.StartTime != 0 {
		n += 1 + sovGift(uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		n += 1 + sovGift(uint64(m.EndTime))
	}
	if m.TimesPerUser != 0 {
		n += 1 + sovGift(uint64(m.TimesPerUser))
	}
	if len(m.ZoneIds) > 0 {
		l = 0
		for _, e := range m.ZoneIds {
			l += sovGift(uint64(e))
		}
		n += 1 + sovGift(uint64(l)) + l
	}
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGift(uint64(l))
		}
	}
	if m.GenerateTime != 0 {
		n += 1 + sovGift(uint64(m.GenerateTime))
	}
	return n
}

func (m *Manager_GenResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGift(uint64(m.Id))
	}
	return n
}

func (m *Manager_ExportReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGift(uint64(m.Id))
	}
	return n
}

func (m *Manager_CodeStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Code)
	if l > 0 {
		n += 1 + l + sovGift(uint64(l))
	}
	if m.UserId != 0 {
		n += 1 + sovGift(uint64(m.UserId))
	}
	if m.ZoneId != 0 {
		n += 1 + sovGift(uint64(m.ZoneId))
	}
	return n
}

func (m *Manager_ExportResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Details) > 0 {
		for _, e := range m.Details {
			l = e.Size()
			n += 1 + l + sovGift(uint64(l))
		}
	}
	return n
}

func (m *Manager_GiftInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGift(uint64(m.Id))
	}
	if m.Used != 0 {
		n += 1 + sovGift(uint64(m.Used))
	}
	if m.GenInfo != nil {
		l = m.GenInfo.Size()
		n += 1 + l + sovGift(uint64(l))
	}
	return n
}

func (m *Manager_ListResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Details) > 0 {
		for _, e := range m.Details {
			l = e.Size()
			n += 1 + l + sovGift(uint64(l))
		}
	}
	return n
}

func (m *Manager_DeleteReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGift(uint64(m.Id))
	}
	return n
}

func (m *VerifyReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Code)
	if l > 0 {
		n += 1 + l + sovGift(uint64(l))
	}
	if m.Zone != 0 {
		n += 1 + sovGift(uint64(m.Zone))
	}
	if m.UserId != 0 {
		n += 1 + sovGift(uint64(m.UserId))
	}
	return n
}

func (m *VerifyResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovGift(uint64(m.Status))
	}
	return n
}

func (m *SyncReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Zone != 0 {
		n += 1 + sovGift(uint64(m.Zone))
	}
	return n
}

func (m *SyncResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Info) > 0 {
		for _, e := range m.Info {
			l = e.Size()
			n += 1 + l + sovGift(uint64(l))
		}
	}
	if m.Status != 0 {
		n += 1 + sovGift(uint64(m.Status))
	}
	return n
}

func sovGift(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGift(x uint64) (n int) {
	return sovGift(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Manager) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Manager: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Manager: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_Nil) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Nil: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Nil: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_Item) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Item: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Item: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num", wireType)
			}
			m.Num = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_GenReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FixCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGift
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FixCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num", wireType)
			}
			m.Num = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimesPerUser", wireType)
			}
			m.TimesPerUser = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimesPerUser |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGift
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint32(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ZoneIds = append(m.ZoneIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGift
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthGift
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ZoneIds) == 0 {
					m.ZoneIds = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGift
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ZoneIds = append(m.ZoneIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneIds", wireType)
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGift
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &Manager_Item{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenerateTime", wireType)
			}
			m.GenerateTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenerateTime |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_GenResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_ExportReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExportReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExportReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_CodeStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CodeStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CodeStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGift
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Code = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneId", wireType)
			}
			m.ZoneId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ZoneId |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_ExportResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExportResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExportResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGift
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Details = append(m.Details, &Manager_CodeStatus{})
			if err := m.Details[len(m.Details)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_GiftInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GiftInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GiftInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Used", wireType)
			}
			m.Used = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Used |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGift
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GenInfo == nil {
				m.GenInfo = &Manager_GenReq{}
			}
			if err := m.GenInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_ListResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGift
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Details = append(m.Details, &Manager_GiftInfo{})
			if err := m.Details[len(m.Details)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Manager_DeleteReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerifyReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifyReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifyReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGift
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Code = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Zone", wireType)
			}
			m.Zone = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Zone |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerifyResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifyResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifyResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Zone", wireType)
			}
			m.Zone = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Zone |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGift
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGift
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Info = append(m.Info, &Manager_GiftInfo{})
			if err := m.Info[len(m.Info)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGift
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGift(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGift
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGift(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGift
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGift
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGift
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGift
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGift
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGift(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGift = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGift   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("gift.proto", fileDescriptor_gift_d27fbfcd8a6c500f) }

var fileDescriptor_gift_d27fbfcd8a6c500f = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x7f, 0x62, 0x27, 0x93, 0xa6, 0x54, 0x03, 0x54, 0x66, 0x0b, 0x56, 0x64, 0x10, 0xb2,
	0x04, 0x44, 0x55, 0x7b, 0x40, 0xe2, 0xc0, 0x01, 0x5a, 0x2a, 0x8b, 0x52, 0x55, 0x0e, 0xe5, 0x80,
	0xb8, 0xb8, 0xf5, 0xa6, 0xb2, 0xd4, 0xda, 0xc6, 0xbb, 0x45, 0xed, 0x5b, 0xf0, 0x24, 0x9c, 0x78,
	0x08, 0x8e, 0x3d, 0x72, 0x44, 0xc9, 0x3b, 0x70, 0x46, 0xb3, 0xb6, 0x13, 0x27, 0x8d, 0x38, 0x65,
	0xe7, 0xff, 0xfb, 0xbe, 0x99, 0x18, 0xe0, 0x2c, 0x19, 0xc9, 0x41, 0x5e, 0x64, 0x32, 0x43, 0x3d,
	0x3f, 0xf1, 0x7e, 0xb6, 0xc0, 0xfe, 0x10, 0xa5, 0xd1, 0x19, 0x2f, 0x58, 0x0b, 0x8c, 0xc3, 0xe4,
	0x9c, 0xf9, 0x60, 0x06, 0x92, 0x5f, 0xe0, 0x1a, 0xe8, 0x41, 0xec, 0x68, 0x7d, 0xcd, 0xef, 0x85,
	0x7a, 0x10, 0xe3, 0x3a, 0x18, 0x87, 0x97, 0x17, 0x8e, 0xde, 0xd7, 0xfc, 0x56, 0x48, 0x4f, 0xf6,
	0x57, 0x03, 0x6b, 0x9f, 0xa7, 0x21, 0xff, 0x8a, 0x0e, 0xd8, 0xef, 0x92, 0xab, 0xb7, 0x59, 0xcc,
	0x55, 0x45, 0x27, 0xac, 0xcd, 0x66, 0x59, 0x4f, 0x95, 0xe1, 0x43, 0xe8, 0x0c, 0x65, 0x54, 0xc8,
	0x8f, 0xc9, 0x05, 0x77, 0x8c, 0xbe, 0xe6, 0x1b, 0xe1, 0xcc, 0x41, 0x9d, 0xf6, 0xd2, 0x58, 0xc5,
	0x4c, 0x15, 0xab, 0x4d, 0xf4, 0x60, 0x95, 0x7e, 0xc5, 0x11, 0x2f, 0x8e, 0x05, 0x2f, 0x9c, 0x96,
	0x6a, 0x39, 0xe7, 0xa3, 0xea, 0xcf, 0x59, 0xca, 0x83, 0x58, 0x38, 0x56, 0xdf, 0xf0, 0x7b, 0x61,
	0x6d, 0xe2, 0x53, 0x68, 0x11, 0x2d, 0xe1, 0xd8, 0x7d, 0xc3, 0xef, 0x6e, 0xaf, 0x0f, 0xf2, 0x93,
	0x41, 0xc5, 0x7c, 0x40, 0x81, 0xb0, 0x0c, 0xd3, 0x94, 0x7d, 0x9e, 0xf2, 0x22, 0x92, 0x5c, 0x81,
	0x68, 0x2b, 0x10, 0x73, 0x3e, 0xf6, 0x00, 0x6c, 0xc5, 0x5b, 0xe4, 0x8b, 0x2a, 0xb1, 0x4d, 0xe8,
	0xec, 0x5d, 0xe5, 0x59, 0x21, 0x49, 0x95, 0xc5, 0xe0, 0x11, 0x00, 0x69, 0x32, 0x94, 0x91, 0xbc,
	0x14, 0x88, 0x60, 0x36, 0x04, 0x53, 0x6f, 0xdc, 0x00, 0x8b, 0x78, 0x04, 0xb1, 0x12, 0xcc, 0x0c,
	0x2b, 0x8b, 0xfc, 0x25, 0x11, 0x25, 0x58, 0x2f, 0xac, 0x2c, 0xf6, 0x1a, 0xa0, 0x1e, 0x27, 0x72,
	0xdc, 0x02, 0x7b, 0x97, 0xcb, 0x28, 0x39, 0x17, 0x8e, 0xa6, 0x58, 0x6e, 0x34, 0x59, 0xce, 0x46,
	0x87, 0x75, 0x1a, 0xfb, 0x02, 0xed, 0xfd, 0x64, 0x24, 0x83, 0x74, 0x94, 0xdd, 0x5a, 0x38, 0x82,
	0x79, 0x2c, 0x78, 0x5c, 0xad, 0x4e, 0xbd, 0xf1, 0xb9, 0x62, 0x4e, 0xe9, 0x0a, 0x48, 0x77, 0x1b,
	0x9b, 0x13, 0xca, 0x63, 0x08, 0xeb, 0x14, 0xf6, 0x0a, 0xda, 0x07, 0x89, 0x28, 0xb1, 0x0d, 0x16,
	0xb1, 0xdd, 0x9b, 0xab, 0xac, 0x40, 0xcc, 0x90, 0x6d, 0x42, 0x67, 0x97, 0x9f, 0x73, 0xc9, 0x97,
	0x08, 0xe9, 0xbd, 0x87, 0xce, 0x27, 0x5e, 0x24, 0xa3, 0x6b, 0x0a, 0x2e, 0xd3, 0x11, 0xc1, 0x24,
	0x85, 0x6a, 0xec, 0xf4, 0x6e, 0x68, 0x6b, 0x34, 0xb5, 0xf5, 0x9e, 0x00, 0xd4, 0xcd, 0x44, 0x4e,
	0x59, 0xa5, 0x48, 0xd5, 0xb8, 0xca, 0xf2, 0x1e, 0x81, 0x3d, 0xbc, 0x4e, 0x4f, 0xab, 0x81, 0xaa,
	0xb9, 0x36, 0x6b, 0xee, 0x1d, 0x40, 0xbb, 0x0c, 0x8b, 0x1c, 0xe9, 0x1f, 0x44, 0x0a, 0xfd, 0x8f,
	0xa7, 0xca, 0x68, 0x0c, 0xd3, 0x9b, 0xc3, 0xb6, 0x7f, 0xe8, 0xd0, 0xa5, 0xd4, 0x21, 0x2f, 0xbe,
	0x25, 0xa7, 0x1c, 0x1f, 0x83, 0x49, 0xdd, 0xb1, 0x4b, 0xbd, 0x2a, 0x18, 0x6c, 0x75, 0x66, 0x88,
	0x7c, 0x4b, 0xc3, 0x67, 0xe5, 0x75, 0x95, 0x5c, 0xb0, 0x47, 0xd1, 0xa9, 0x48, 0x6c, 0xad, 0x69,
	0x8a, 0x1c, 0x77, 0xa0, 0x5d, 0x9f, 0x34, 0x2e, 0xd9, 0x21, 0xbb, 0x7b, 0xcb, 0x27, 0x72, 0x7c,
	0x01, 0x26, 0xed, 0x13, 0xef, 0x34, 0x83, 0xf4, 0xcd, 0x98, 0xe3, 0x38, 0x5d, 0xf9, 0x4b, 0xb0,
	0xca, 0xe3, 0xc4, 0xfb, 0xcd, 0xf8, 0xf4, 0xff, 0xc1, 0x36, 0x96, 0xb9, 0xd5, 0x1d, 0x5b, 0xe5,
	0xee, 0xe7, 0x0b, 0xa7, 0xf7, 0xc0, 0x16, 0x01, 0xbc, 0x71, 0x7e, 0x8d, 0x5d, 0xed, 0x66, 0xec,
	0x6a, 0x7f, 0xc6, 0xae, 0xf6, 0x7d, 0xe2, 0xae, 0xdc, 0x4c, 0xdc, 0x95, 0xdf, 0x13, 0x77, 0xe5,
	0xc4, 0x52, 0x1f, 0xbb, 0x9d, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x50, 0x4b, 0xb9, 0xc2, 0xfa,
	0x04, 0x00, 0x00,
}
